export const ActivityActionTypes = {
  ADD_ACTIVITY: 'ADD_ACTIVITY'
}

export const GET_ACTIVITIES = {
  BEGIN: 'GET_ACTIVITIES_BEGIN',
  SUCCESS: 'GET_ACTIVITIES_SUCCESS',
  FAILURE: 'GET_ACTIVITIES_FAILURE'
}
